### ISSUE TITLE
Script to allow for bulk edits to CryptoProfile objects Cipher attributes

### ISSUE THREAD

**Issue by iLoveTux** [McIndi/mast#1]
We need a script which will allow a user to edit the Cipher attribute of multiple CryptoProfile objects.

First iteration will be in the form of a contrib script.

Any ideas anyone has are welcome below.

@briankearney @mharden108 @steveyeof

**Comment by jimb400** [comment]
I would love to keep this more generic where we can modify properties of multiple objects of the same object class. Either pass a delimited list, specify ALL of possibly a reggae match? Kind of like a on the fly deployment policy?


Could even use a deployment policy by exporting all of that object type, creating a deployment policy and then re-importing applying the deployment policy. Just some thoughts but I have had many use cases where this would come in handy. Like

1. Update all HTTP and HTTPS FSH objects listening on loopback with persistent connection on to persistent connections off.
2. Synchronize ALL WSRR subscription objects

Many more but a couple of examples of a filter and an ALL.

**Comment by iLoveTux** [comment]
That's a great idea. There is an easier way, although it has one draw-back. The SOMA has a modify-config option which will take just the updated values and apply them to an existing object. It would be very simple to provide this functionality to the user.

The only real drawback is when the attribute can exist multiple times on a configuration object (SecondaryAddress on an EthernetInterface for instance), all values are replaced.

I think this is the only scenario where this happens, but I've heard these things refered to as "`vector adds`". I don't know if this is acceptable or not. There is some code [here] (https://github.com/McIndi/mast.datapower.datapower/blob/master/mast/datapower/datapower/DataPower.py#L3050-L3084) with one way to overcome this problem, but it would be kind of hard to make this solution more generic without an up-to-date list of all required "`vector adds`" and then we would have to maintain that list, unless there is some way to generate it from the `wsdl`s or `xsd`s

We could however, make the user pass in a `--vector-add` flag in which case we could assume that a `vector add` must be performed. This would put the burden on the user, so we would need a warning and a better definition of what exactly a `vector add` is.

 Please let me know what you think.

**Comment by iLoveTux** [comment]
@jimb400 @briankearney @mharden108 @steveyeof 

Here is [a link to the file](https://raw.githubusercontent.com/McIndi/mast.installer/modify-config-1/mast/installer/files/contrib/modify-config.py) (right-click -> Save As)

Please see the [pull request](https://github.com/McIndi/mast.installer/pull/6) for some usage instructions. Also this is a rough draft and a totally new script, so code review will be greatly appreciated.

**Comment by iLoveTux** [comment]
Serious [bug](https://github.com/McIndi/mast.installer/pull/6#issuecomment-201227389) found in the current pull request. I am working on a fix, and will update here when done.

**Comment by iLoveTux** [comment]
OK, I think we have most of it ironed out. See comment [here](https://github.com/McIndi/mast.installer/pull/6#issuecomment-201499666)

**Comment by iLoveTux** [comment]
This issue was resolved by [this commit](https://github.com/McIndi/mast.installer/commit/7474a1c17591ce186b3d5261c8d3e6217e7c7d5d).

Closing issue.
