### ISSUE TITLE
bad formatting in CLIReference.md

### ISSUE THREAD

**Issue by iLoveTux** [McIndi/mast#14]
The auto-generated documentation mangles the formatting in CLIReference.md for mast-crypto.bat.

**Comment by iLoveTux** [comment]
Found the problem see [here](https://github.com/McIndi/mast.installer/blob/fix-doc-formatting/mast/installer/files/contrib/gendocs.py#L297-L298)

**Comment by iLoveTux** [comment]
We will need to comment what we're doing [here](https://github.com/McIndi/mast.installer/blob/fix-doc-formatting/mast/installer/files/contrib/gendocs.py#L293-L301) and why as part of the solution to this issue

**Comment by iLoveTux** [comment]
Think I fixed the issue take a look at the [updated file](https://raw.githubusercontent.com/McIndi/mast.installer/fix-doc-formatting/mast/installer/files/contrib/gendocs.py) (Right-Click -> Save As)

**Comment by iLoveTux** [comment]
[Pull request](https://github.com/McIndi/mast.installer/pull/11) created, still need to comment whats going on with [these](https://github.com/McIndi/mast.installer/blob/fix-doc-formatting/mast/installer/files/contrib/gendocs.py#L293-L301) regular expressions, but we can test the fix for now.

**Comment by iLoveTux** [comment]
Pull request was merged.

**Comment by steveyeof** [comment]
Maybe clarify the comment on line 298 that section headers refer mast main commands.See
[here](https://github.com/McIndi/mast.installer/blob/fix-doc-formatting/mast/installer/files/contrib/gendocs.py#L298-L298) for example.

**Comment by iLoveTux** [comment]
The problem is that they don't.

see here (the help message from `mast-accounts`)

```
$ ./mast-accounts --help
A command must be specified. 

General Commands:
  help - Prints the global help message listing all commands.
users/groups Commands:
  list-groups - Display a list of all configured user groups on the specified appliances, along with a list of the groups common to all appliances.
  add-group - Adds a user group to the specified appliances.
  del-group - Removes a user group from the specified appliances.
  list-users - Lists the users on the specified appliances as well as a list of users common to all appliances.
  add-user - Adds a user to the specified appliances.
  del-user - Removes a user from the specified appliances.
  change-password - Changes the specified user's password to the specified password.
  force-change-password - Forces a user to change their password on their next login.
  list-rbm-fallback - Lists the current RBM Fallback Users for the specified appliances, as well as the fallback users which are common to all appliances.
  add-rbm-fallback - Adds a user to the the RBM Fallback users.
  del-rbm-fallback - Removes a user from the the RBM Fallback users.
caches Commands:
  flush-aaa-cache - Flushes the AAA Cache of the specified aaa_policy in the specified Domain.
  flush-ldap-pool-cache - Flushes the LDAP Pool Cache for the specified xml_manager in the specified domain.
  flush-rbm-cache - Flush the RBM Cache in the specified Domain
```

The lines we are targeting with that regex are:

* `General Commands:`
* `users/groups Commands:`
* `caches Commands:`

These are categories of sub-commands, not mast main commands. So we are trying to create a section in the docs for  each category of sub-command.

I will happily, however clarify the comment to reflect that.

**Comment by iLoveTux** [comment]
The [pull request](https://github.com/McIndi/mast.installer/pull/11) updated, take a look @steveyeof

**Comment by iLoveTux** [comment]
Pull request merged, closing.
