### ISSUE TITLE
Weekly release schedule

### ISSUE THREAD

**Issue by iLoveTux** [McIndi/mast#19]
I would love to have a weekly release schedule (with nightly builds). We could use GitHub's Milestone feature to track which issues will be addressed in each release in order to make things more concrete.

Also on an unrelated note I would recommend that everyone read [this short page](https://guides.github.com/features/issues/) regarding github issues so we can be on the same page.

**Comment by iLoveTux** [comment]
Just as a side note, getting everything ready for weekly releases, we should also tag nightly builds and automate the process of building the installers

**Comment by steveyeof** [comment]
This Is certainly in keeping continuous integration goals, and automating the building of installers is awesome, but do we need to resolve the version numbering standards issue #18 before moving to more frequent releases? I am today looking into the version numbering question and will comment in that issue space.

**Comment by iLoveTux** [comment]
I mean, I'm in favor of both of these issues, but order is irrelevant, we can easily change versioning standards later. Although the other way is fine too,

**Comment by steveyeof** [comment]
If you've got something well along go with it, I'll get to the other by the end of day.

**Comment by iLoveTux** [comment]
I'm going to push this back to mast 3, but maybe give myself some more leeway with maybe a monthly release.
