### ISSUE TITLE
Script to gather information for support

### ISSUE THREAD

**Issue by iLoveTux** [McIndi/mast#21]
We need a script which does the following (open to suggestions, but lets keep the first version simple):

1. Gather the versions of all installed packages
2. Gather all logs
3. Asks certain questions to help with documentation
    * What did you expect to happen
    * What actually happened
    * What was the output of the command
4. Zip everything up for the user to send to us

**Comment by steveyeof** [comment]
I like it looks pretty complete, can't resist an "idea" to complicate it later. Could this zip be produced as part of the output (for certain failure conditions) from the selenium test suite? The intent is to produce reference cheat sheets to aid troubleshooting, just an "idea"

**Comment by iLoveTux** [comment]
I think that's what we are producing here in github issues. We just need to be sure to be as informative and thorough as possible.

**Comment by iLoveTux** [comment]
This will need to be added in MAST 3
