### ISSUE TITLE
trouble with build-hotfix.py

### ISSUE THREAD

**Issue by briankearney** [McIndi/mast#27]
#### _Issue template for MAST for IBM DataPower_

This is may be a problem with the proxy that I am behind right now, but build-hotfix.py is throwing this error, even after changing the order of the URLs in the script and adding "verify=False" to the requests:

https://github.com/McIndi/mast.cli/archive/master.zip
Traceback (most recent call last):
  File "contrib\build-hotfix.py", line 386, in <module>
    cli.run()
  File "build\bdist.win-amd64\egg\mast\cli\__init__.py", line 250, in run
  File "contrib\build-hotfix.py", line 324, in main
    resp = requests.get(repo, verify="False")
  File "C:\temp\mast\anaconda\lib\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "C:\temp\mast\anaconda\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\temp\mast\anaconda\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\temp\mast\anaconda\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\temp\mast\anaconda\lib\site-packages\requests\adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 2] No such file or directory

I tried verifying that URL with wget and it suceeded:

$ wget --no-check-certificate https://github.com/McIndi/mast.config/archive/master.zip
--2016-04-06 11:27:56--  https://github.com/McIndi/mast.config/archive/master.zip
Resolving github.com (github.com)... 192.30.252.120
Connecting to github.com (github.com)|192.30.252.120|:443... connected.
WARNING: The certificate of ‘github.com’ is not trusted.
WARNING: The certificate of ‘github.com’ hasn't got a known issuer.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/McIndi/mast.config/zip/master [following]
--2016-04-06 11:27:57--  https://codeload.github.com/McIndi/mast.config/zip/master
Resolving codeload.github.com (codeload.github.com)... 192.30.252.161
Connecting to codeload.github.com (codeload.github.com)|192.30.252.161|:443... connected.
WARNING: The certificate of ‘codeload.github.com’ is not trusted.
WARNING: The certificate of ‘codeload.github.com’ hasn't got a known issuer.
HTTP request sent, awaiting response... 200 OK
Length: 3233 (3.2K) [application/zip]
Saving to: ‘master.zip’

master.zip                           100%[====================================================================>]   3.16K  --.-KB/s    in 0.002s

2016-04-06 11:27:57 (1.30 MB/s) - ‘master.zip’ saved [3233/3233]

1. update to the latest and greatest
2. using build-hotfix -i, i expected that all the latest commits on github would be installed locally
3. see the output / errors above
4. i was successful with installing a hotfix, using the same procedure, within the last 2 or 3 weeks

“I’m not just the president of Hair Club for Men, I’m also a client!”

**Comment by iLoveTux** [comment]
(Please forgive and correct me if my terminology is incorrect)

Found it! This one was tricky. the `verify` parameter can be set to `False` to disable SSL/TLS verification, but it can also be set to a string indicating the path to your CACert (trusted root certificates).

You set it equal to `"False"` instead of `False` (notice the quotes), by setting it to a string it thinks your giving it the path to your trusted root certificates.

__tldr__

You can work around this by changing `"False"` to `False`.

I will create a pull request which will expose a `-v, --verify` option to `build-hotfix.py` to prevent people from having to hack the source to disable SSL/TLS verification, you and I have talked about this before, but now it's in GitHub so I will get it done very soon.

**Comment by iLoveTux** [comment]
This is fixed in commit McIndi/mast.installer@aa79c33 but made it `--no-verify` instead so that the default is to verify.
