### ISSUE TITLE
ER: assimilation / configuration script & tab

### ISSUE THREAD

**Issue by briankearney** [McIndi/mast#35]
#### _Issue template for MAST for IBM DataPower_

_Please give a brief description of the issue you are having_
This is an Enhancement Request to implement a "assimilation" or configuration script (CLI) & tab (GUI) for key, cert, environment, hosts, address, port, log file, log level, mutual auth, etc. configuration changes. I propose that the "tab" in the GUI be separated from the rest of the and protected via TLS mutual auth.

_Please answer each question as best as you can_

1. **What were you trying to do?** Manage and change the configuration of MAST in a manner consistent with the rest of the funtionality in MAST
2. **What were you expecting to happen?** Nothing, this functionality does not currently exist
3. **What were the actual results?** None, as expected
4. **Was this a fresh install of MAST or when was the last time you installed a hotfix?** yes, both
5. **Please provide any output from the command (If in the web gui click the `history` link in the output and paste that).** N/A

Thank you for taking the time to submit an issue, this is the only way we can continue to improve MAST in response to our customers needs.

**Comment by iLoveTux** [comment]
again, this will be implemented in MAST 3
