### ISSUE TITLE
ER: auto-complete in GUI

### ISSUE THREAD

**Issue by briankearney** [McIndi/mast#36]
#### _Issue template for MAST for IBM DataPower_

_Please give a brief description of the issue you are having_
This is an Enhancement Request to implement auto-complete in the GUI (with a config option to enable / disable the auto-complete, that defaults to disabled) and a radio button that activates a drop-down list of the configured hosts and environments. Since the host / environment issue might "leak" some information, I think it  that there should be an option to require TLS mutual auth in the GUI.

Should TLS mutual auth in the GUI be a separate ER? 

This feature was requested by a consultant that is trest driving MAST.

_Please answer each question as best as you can_

1. **What were you trying to do?** have the browser auto-complete the host/env, username and/or password fields or, at least, have a drop-down list of the hosts / envs
2. **What were you expecting to happen?** Nothing, this feature does not exist
3. **What were the actual results?** None, as expected
4. **Was this a fresh install of MAST or when was the last time you installed a hotfix?** yes, both
5. **Please provide any output from the command (If in the web gui click the `history` link in the output and paste that).** N/A

Thank you for taking the time to submit an issue, this is the only way we can continue to improve MAST in response to our customers needs.

**Comment by iLoveTux** [comment]
I believe that this will have to wait for MAST 3 as no major changes are slated for the web gui in the MAST 2 series.
