### ISSUE TITLE
ER: appliance reboot should have an option to quiesce first

### ISSUE THREAD

**Issue by briankearney** [McIndi/mast#38]
#### _Issue template for MAST for IBM DataPower_

_Please give a brief description of the issue you are having_
It would be a functional and usability enhancement if there was an option to quiesce the appliance before rebooting

_Please answer each question as best as you can_

1. **What were you trying to do?** gracefully reboot an appliance
2. **What were you expecting to happen?** quiesce and then reboot
3. **What were the actual results?** no quiesce option, so just had to reboot
4. **Was this a fresh install of MAST or when was the last time you installed a hotfix?** last hotdfix was 03/30/2016
5. **Please provide any output from the command (If in the web gui click the `history` link in the output and paste that).**
./mast-system reboot-appliance -h
Documentation for command 'reboot-appliance':
----------------------------------------
Reboot the specified appliances (equivalent to shutdown-reboot)

Parameters:

* `-a, --appliances`: The hostname(s), ip address(es), environment name(s)
or alias(es) of the appliances you would like to affect. For details
on configuring environments please see the comments in
`environments.conf` located in `$MAST_HOME/etc/default`. For details
on configuring aliases, please see the comments in `hosts.conf` located in
`$MAST_HOME/etc/default`. To pass multiple arguments to this parameter,
use multiple entries of the form `[-a appliance1 [-a appliance2...]]`
* `-c, --credentials`: The credentials to use for authenticating to the
appliances. Should be either one set to use for all appliances
or one set for each appliance. Credentials should be in the form
`username:password`. To pass multiple credentials to this parameter, use
multiple entries of the form `[-c credential1 [-c credential2...]]`.
When referencing multiple appliances with multiple credentials,
there must be a one-to-one correspondence of credentials to appliances:
`[-a appliance1 [-a appliance2...]] [-c credential1 [-c credential2...]]`
If you would prefer to not use plain-text passwords,
you can use the output of `$ mast-system xor <username:password>`.
* `-t, --timeout`: The timeout in seconds to wait for a response from
an appliance for any single request. __NOTE__ Program execution may
halt if a timeout is reached.
* `-n, --no-check-hostname`: If specified SSL verification will be turned
off when sending commands to the appliances.
* `-d, --delay`: The delay before rebooting
* `-w, --wait`: The amount of time to wait for all appliances
to come back up
* `-W, --web`: __For Internel Use Only, will be removed in future versions.
DO NOT USE.__
----------------------------------------

Usage: mast-system reboot-appliance [options]
Options without default values MUST be specified

Use: mast-system help [command]
  to see other commands available.

Options:
  -h, --help            
  -a APPLIANCES, --appliances=APPLIANCES
  -c CREDENTIALS, --credentials=CREDENTIALS
  -t TIMEOUT, --timeout=TIMEOUT
                        [default: 120]
  -n, --no-check-hostname
  -d DELAY, --delay=DELAY
                        [default: 10]
  -w WAIT, --wait=WAIT  [default: 1200]
  -W, --web             

Thank you for taking the time to submit an issue, this is the only way we can continue to improve MAST in response to our customers needs.

**Comment by iLoveTux** [comment]
Sounds like a great idea and simple to do. I'll add it in tomorrow.

**Comment by briankearney** [comment]
With best practices in mind, we should default to quiescent before reboot
and have an option to --skip-quiesce?
On Apr 19, 2016 12:10 AM, "Clifford Bressette" <notifications@github.com>
wrote:

Sounds like a great idea and simple to do. I'll add it in tomorrow.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/McIndi/mast/issues/38#issuecomment-211721569>
