### ISSUE TITLE
did cherrypy do something weird to their git history?

### ISSUE THREAD

**Issue by briankearney** [McIndi/mast#45]
#### _Issue template for MAST for IBM DataPower_

_Please give a brief description of the issue you are having_
While attempting to recursively clone mast.installer with git, I received an error about cherrypy

_Please answer each question as best as you can_

1. **What were you trying to do?**
Execute the "git clone --recursive https://github.com/McIndi/mast.installer" command

2. **What were you expecting to happen?**
A successful, recursive clone of mast.installer 

3. **What were the actual results?**
Fetched in submodule path 'mast/installer/packages/cherrypy', but it did not contain 7b0e26425e7fb661b1981d46ea90dedec36afe52. Direct fetching of that commit failed. 

4. **Was this a fresh install of MAST or when was the last time you installed a hotfix?**
No, this was an attempt to perform a fresh recursive clone

5. **Please provide any output from the command (If in the web gui click the `history` link in the output and paste that).**

Cloning into 'mast.installer'...
remote: Counting objects: 2933, done.
remote: Total 2933 (delta 0), reused 0 (delta 0), pack-reused 2932
Receiving objects: 100% (2933/2933), 1.98 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1792/1792), done.
Checking connectivity... done.
...........
Submodule ...
Submodule ...
Submodule ...
........... 
Cloning into 'mast/installer/packages/cherrypy'...
remote: Counting objects: 22582, done.
remote: Total 22582 (delta 0), reused 0 (delta 0), pack-reused 22582
Receiving objects: 100% (22582/22582), 26.18 MiB | 13.00 MiB/s, done.
Resolving deltas: 100% (3701/3701), done.
Checking connectivity... done.
error: no such remote ref 7b0e26425e7fb661b1981d46ea90dedec36afe52
Fetched in submodule path 'mast/installer/packages/cherrypy', but it did not contain 7b0e26425e7fb661b1981d46ea90dedec36afe52. Direct fetching of that commit failed. 

Thank you for taking the time to submit an issue, this is the only way we can continue to improve MAST in response to our customers needs.

**Comment by iLoveTux** [comment]
I can't really tell what happened to their history, maybe I need more experience with git. The commit we were pointing to does seem to exist [here](https://github.com/cherrypy/cherrypy/tree/7b0e26425e7fb661b1981d46ea90dedec36afe52), but we can't check it out.

I did manage to fix this issue on our end by pointing to the latest commit on cherrypy, you can see the change [here](https://github.com/McIndi/mast.installer/commit/326fe766a47a1e7b54874ede67511863081a9a62)

**Comment by iLoveTux** [comment]
closing this issue
