### ISSUE TITLE
build-hotfix -i fails with encoding error

### ISSUE THREAD

**Issue by briankearney** [McIndi/mast#55]
#### _Issue template for MAST for IBM DataPower_

_Please give a brief description of the issue you are having_

_Please answer each question as best as you can_

1. **What were you trying to do?** build-hotfix -i
2. **What were you expecting to happen?** get the latest fixes installed
3. **What were the actual results?** UnicodeEncodeError: 'charmap' codec can't encode characters in position 37-41: character maps to <undefined>
4. **Was this a fresh install of MAST or when was the last time you installed a hotfix?** fresh install of mast (MAST_2.1.1_Windows-64_install.exe)
5. **Please provide any output from the command (If in the web gui click the `history` link in the output and paste that).**

https://github.com/McIndi/mast.cli/archive/master.zip
        mast.cli-master/
        mast.cli-master/.gitignore
        mast.cli-master/README.md
        mast.cli-master/mast/
        mast.cli-master/mast/__init__.py
        mast.cli-master/mast/cli/
        mast.cli-master/mast/cli/__init__.py
        mast.cli-master/setup.py
https://github.com/McIndi/mast.config/archive/master.zip
        mast.config-master/
        mast.config-master/.gitignore
        mast.config-master/README.md
        mast.config-master/mast/
        mast.config-master/mast/__init__.py
        mast.config-master/mast/config/
        mast.config-master/mast/config/__init__.py
        mast.config-master/setup.py
https://github.com/McIndi/mast.cron/archive/master.zip
        mast.cron-master/
        mast.cron-master/.gitignore
        mast.cron-master/README.md
        mast.cron-master/mast/
        mast.cron-master/mast/__init__.py
        mast.cron-master/mast/cron/
        mast.cron-master/mast/cron/__init__.py
        mast.cron-master/setup.py
https://github.com/McIndi/mast.daemon/archive/master.zip
        mast.daemon-master/
        mast.daemon-master/.gitignore
        mast.daemon-master/README.md
        mast.daemon-master/mast/
        mast.daemon-master/mast/__init__.py
        mast.daemon-master/mast/daemon/
        mast.daemon-master/mast/daemon/__init__.py
        mast.daemon-master/mast/daemon/__main__.py
        mast.daemon-master/mast/daemon/mast_daemon.py
        mast.daemon-master/setup.py
https://github.com/McIndi/mast.datapower.accounts/archive/master.zip
        mast.datapower.accounts-master/
        mast.datapower.accounts-master/.gitignore
        mast.datapower.accounts-master/README.md
        mast.datapower.accounts-master/mast/
        mast.datapower.accounts-master/mast/__init__.py
        mast.datapower.accounts-master/mast/datapower/
        mast.datapower.accounts-master/mast/datapower/__init__.py
        mast.datapower.accounts-master/mast/datapower/accounts/
        mast.datapower.accounts-master/mast/datapower/accounts/__init__.py
        mast.datapower.accounts-master/mast/datapower/accounts/__main__.py
        mast.datapower.accounts-master/mast/datapower/accounts/accounts.py
        mast.datapower.accounts-master/mast/datapower/accounts/docroot/
        mast.datapower.accounts-master/mast/datapower/accounts/docroot/plugin.css
        mast.datapower.accounts-master/mast/datapower/accounts/docroot/plugin.js
        mast.datapower.accounts-master/setup.py
https://github.com/McIndi/mast.datapower.backups/archive/master.zip
        mast.datapower.backups-master/
        mast.datapower.backups-master/.gitignore
        mast.datapower.backups-master/README.md
        mast.datapower.backups-master/mast/
        mast.datapower.backups-master/mast/__init__.py
        mast.datapower.backups-master/mast/datapower/
        mast.datapower.backups-master/mast/datapower/__init__.py
        mast.datapower.backups-master/mast/datapower/backups/
        mast.datapower.backups-master/mast/datapower/backups/__init__.py
        mast.datapower.backups-master/mast/datapower/backups/__main__.py
        mast.datapower.backups-master/mast/datapower/backups/backups.py
        mast.datapower.backups-master/mast/datapower/backups/docroot/
        mast.datapower.backups-master/mast/datapower/backups/docroot/plugin.css
        mast.datapower.backups-master/mast/datapower/backups/docroot/plugin.js
        mast.datapower.backups-master/setup.py
https://github.com/McIndi/mast.datapower.crypto/archive/master.zip
        mast.datapower.crypto-master/
        mast.datapower.crypto-master/.gitignore
        mast.datapower.crypto-master/LICENSE
        mast.datapower.crypto-master/README.md
        mast.datapower.crypto-master/mast/
        mast.datapower.crypto-master/mast/__init__.py
        mast.datapower.crypto-master/mast/datapower/
        mast.datapower.crypto-master/mast/datapower/__init__.py
        mast.datapower.crypto-master/mast/datapower/crypto/
        mast.datapower.crypto-master/mast/datapower/crypto/__init__.py
        mast.datapower.crypto-master/mast/datapower/crypto/__main__.py
        mast.datapower.crypto-master/mast/datapower/crypto/docroot/
        mast.datapower.crypto-master/mast/datapower/crypto/docroot/plugin.css
        mast.datapower.crypto-master/mast/datapower/crypto/docroot/plugin.js
        mast.datapower.crypto-master/mast/datapower/crypto/utils.py
        mast.datapower.crypto-master/setup.py
https://github.com/McIndi/mast.datapower.datapower/archive/master.zip
        mast.datapower.datapower-master/
        mast.datapower.datapower-master/.gitignore
        mast.datapower.datapower-master/README.md
        mast.datapower.datapower-master/mast/
        mast.datapower.datapower-master/mast/__init__.py
        mast.datapower.datapower-master/mast/datapower/
        mast.datapower.datapower-master/mast/datapower/__init__.py
        mast.datapower.datapower-master/mast/datapower/datapower/
        mast.datapower.datapower-master/mast/datapower/datapower/DataPower.py
        mast.datapower.datapower-master/mast/datapower/datapower/WSClientLib.py
        mast.datapower.datapower-master/mast/datapower/datapower/__init__.py
        mast.datapower.datapower-master/mast/datapower/datapower/dpSOMALib.py
        mast.datapower.datapower-master/mast/datapower/datapower/environment.py
        mast.datapower.datapower-master/mast/datapower/datapower/et/
        mast.datapower.datapower-master/mast/datapower/datapower/et/ElementInclude.py
        mast.datapower.datapower-master/mast/datapower/datapower/et/ElementPath.py
        mast.datapower.datapower-master/mast/datapower/datapower/et/ElementTree.py
        mast.datapower.datapower-master/mast/datapower/datapower/et/__init__.py
        mast.datapower.datapower-master/setup.py
https://github.com/McIndi/mast.datapower.deploy/archive/master.zip
        mast.datapower.deploy-master/
        mast.datapower.deploy-master/.gitignore
        mast.datapower.deploy-master/README.md
        mast.datapower.deploy-master/mast/
        mast.datapower.deploy-master/mast/__init__.py
        mast.datapower.deploy-master/mast/datapower/
        mast.datapower.deploy-master/mast/datapower/__init__.py
        mast.datapower.deploy-master/mast/datapower/deploy/
        mast.datapower.deploy-master/mast/datapower/deploy/__init__.py
        mast.datapower.deploy-master/mast/datapower/deploy/__main__.py
        mast.datapower.deploy-master/mast/datapower/deploy/data/
        mast.datapower.deploy-master/mast/datapower/deploy/data/deploy.conf
        mast.datapower.deploy-master/mast/datapower/deploy/deploy.py
        mast.datapower.deploy-master/setup.py
https://github.com/McIndi/mast.datapower.deployment/archive/master.zip
        mast.datapower.deployment-master/
        mast.datapower.deployment-master/.gitignore
        mast.datapower.deployment-master/README.md
        mast.datapower.deployment-master/mast/
        mast.datapower.deployment-master/mast/__init__.py
        mast.datapower.deployment-master/mast/datapower/
        mast.datapower.deployment-master/mast/datapower/__init__.py
        mast.datapower.deployment-master/mast/datapower/deployment/
        mast.datapower.deployment-master/mast/datapower/deployment/__init__.py
        mast.datapower.deployment-master/mast/datapower/deployment/__main__.py
        mast.datapower.deployment-master/mast/datapower/deployment/deployment.py
        mast.datapower.deployment-master/mast/datapower/deployment/docroot/
        mast.datapower.deployment-master/mast/datapower/deployment/docroot/plugin.css
        mast.datapower.deployment-master/mast/datapower/deployment/docroot/plugin.js
        mast.datapower.deployment-master/setup.py
https://github.com/McIndi/mast.datapower.developer/archive/master.zip
        mast.datapower.developer-master/
        mast.datapower.developer-master/.gitignore
        mast.datapower.developer-master/README.md
        mast.datapower.developer-master/mast/
        mast.datapower.developer-master/mast/__init__.py
        mast.datapower.developer-master/mast/datapower/
        mast.datapower.developer-master/mast/datapower/__init__.py
        mast.datapower.developer-master/mast/datapower/developer/
        mast.datapower.developer-master/mast/datapower/developer/__init__.py
        mast.datapower.developer-master/mast/datapower/developer/__main__.py
        mast.datapower.developer-master/mast/datapower/developer/developer.py
        mast.datapower.developer-master/mast/datapower/developer/docroot/
        mast.datapower.developer-master/mast/datapower/developer/docroot/plugin.css
        mast.datapower.developer-master/mast/datapower/developer/docroot/plugin.js
        mast.datapower.developer-master/setup.py
https://github.com/McIndi/mast.datapower.network/archive/master.zip
        mast.datapower.network-master/
        mast.datapower.network-master/.gitignore
        mast.datapower.network-master/README.md
        mast.datapower.network-master/mast/
        mast.datapower.network-master/mast/__init__.py
        mast.datapower.network-master/mast/datapower/
        mast.datapower.network-master/mast/datapower/__init__.py
        mast.datapower.network-master/mast/datapower/network/
        mast.datapower.network-master/mast/datapower/network/__init__.py
        mast.datapower.network-master/mast/datapower/network/__main__.py
        mast.datapower.network-master/mast/datapower/network/docroot/
        mast.datapower.network-master/mast/datapower/network/docroot/plugin.css
        mast.datapower.network-master/mast/datapower/network/docroot/plugin.js
        mast.datapower.network-master/mast/datapower/network/network.py
        mast.datapower.network-master/setup.py
https://github.com/McIndi/mast.datapower.ssh/archive/master.zip
        mast.datapower.ssh-master/
        mast.datapower.ssh-master/.gitignore
        mast.datapower.ssh-master/README.md
        mast.datapower.ssh-master/mast/
        mast.datapower.ssh-master/mast/__init__.py
        mast.datapower.ssh-master/mast/datapower/
        mast.datapower.ssh-master/mast/datapower/__init__.py
        mast.datapower.ssh-master/mast/datapower/ssh/
        mast.datapower.ssh-master/mast/datapower/ssh/__init__.py
        mast.datapower.ssh-master/mast/datapower/ssh/__main__.py
        mast.datapower.ssh-master/mast/datapower/ssh/docroot/
        mast.datapower.ssh-master/mast/datapower/ssh/docroot/plugin.css
        mast.datapower.ssh-master/mast/datapower/ssh/docroot/plugin.html
        mast.datapower.ssh-master/mast/datapower/ssh/docroot/plugin.js
        mast.datapower.ssh-master/mast/datapower/ssh/ssh.py
        mast.datapower.ssh-master/setup.py
https://github.com/McIndi/mast.datapower.status/archive/master.zip
        mast.datapower.status-master/
        mast.datapower.status-master/.gitignore
        mast.datapower.status-master/README.md
        mast.datapower.status-master/mast/
        mast.datapower.status-master/mast/__init__.py
        mast.datapower.status-master/mast/datapower/
        mast.datapower.status-master/mast/datapower/__init__.py
        mast.datapower.status-master/mast/datapower/status/
        mast.datapower.status-master/mast/datapower/status/__init__.py
        mast.datapower.status-master/mast/datapower/status/docroot/
        mast.datapower.status-master/mast/datapower/status/docroot/plugin.conf
        mast.datapower.status-master/mast/datapower/status/docroot/plugin.css
        mast.datapower.status-master/mast/datapower/status/docroot/plugin.html
        mast.datapower.status-master/mast/datapower/status/docroot/plugin.js
        mast.datapower.status-master/mast/datapower/status/status.py
        mast.datapower.status-master/setup.py
https://github.com/mcindi/mast.datapower.system/archive/master.zip
        mast.datapower.system-master/
        mast.datapower.system-master/.gitignore
        mast.datapower.system-master/README.md
        mast.datapower.system-master/mast/
        mast.datapower.system-master/mast/__init__.py
        mast.datapower.system-master/mast/datapower/
        mast.datapower.system-master/mast/datapower/__init__.py
        mast.datapower.system-master/mast/datapower/system/
        mast.datapower.system-master/mast/datapower/system/__init__.py
        mast.datapower.system-master/mast/datapower/system/__main__.py
        mast.datapower.system-master/mast/datapower/system/docroot/
        mast.datapower.system-master/mast/datapower/system/docroot/plugin.css
        mast.datapower.system-master/mast/datapower/system/docroot/plugin.js
        mast.datapower.system-master/mast/datapower/system/system.py
        mast.datapower.system-master/setup.py
https://github.com/mcindi/mast.datapower.web/archive/master.zip
        mast.datapower.web-master/
        mast.datapower.web-master/.gitignore
        mast.datapower.web-master/README.md
        mast.datapower.web-master/mast/
        mast.datapower.web-master/mast/__init__.py
        mast.datapower.web-master/mast/datapower/
        mast.datapower.web-master/mast/datapower/__init__.py
        mast.datapower.web-master/mast/datapower/web/
        mast.datapower.web-master/mast/datapower/web/__init__.py
        mast.datapower.web-master/mast/datapower/web/__main__.py
        mast.datapower.web-master/mast/datapower/web/gui.py
        mast.datapower.web-master/setup.py
https://github.com/mcindi/mast.hashes/archive/master.zip
        mast.hashes-master/
        mast.hashes-master/.gitignore
        mast.hashes-master/README.md
        mast.hashes-master/mast/
        mast.hashes-master/mast/__init__.py
        mast.hashes-master/mast/hashes/
        mast.hashes-master/mast/hashes/__init__.py
        mast.hashes-master/setup.py
https://github.com/mcindi/mast.logging/archive/master.zip
        mast.logging-master/
        mast.logging-master/.gitignore
        mast.logging-master/README.md
        mast.logging-master/mast/
        mast.logging-master/mast/__init__.py
        mast.logging-master/mast/__init__.pyc
        mast.logging-master/mast/logging/
        mast.logging-master/mast/logging/__init__.py
        mast.logging-master/mast/logging/__init__.pyc
        mast.logging-master/setup.py
https://github.com/mcindi/mast.plugins/archive/master.zip
        mast.plugins-master/
        mast.plugins-master/.gitignore
        mast.plugins-master/README.md
        mast.plugins-master/mast/
        mast.plugins-master/mast/__init__.py
        mast.plugins-master/mast/plugins/
        mast.plugins-master/mast/plugins/__init__.py
        mast.plugins-master/mast/plugins/web.py
        mast.plugins-master/setup.py
https://github.com/mcindi/mast.plugin_utils/archive/master.zip
        mast.plugin_utils-master/
        mast.plugin_utils-master/.gitignore
        mast.plugin_utils-master/README.md
        mast.plugin_utils-master/mast/
        mast.plugin_utils-master/mast/__init__.py
        mast.plugin_utils-master/mast/plugin_utils/
        mast.plugin_utils-master/mast/plugin_utils/__init__.py
        mast.plugin_utils-master/mast/plugin_utils/plugin_functions.py
        mast.plugin_utils-master/mast/plugin_utils/plugin_utils.py
        mast.plugin_utils-master/setup.py
https://github.com/mcindi/mast.pprint/archive/master.zip
        mast.pprint-master/
        mast.pprint-master/.gitignore
        mast.pprint-master/README.md
        mast.pprint-master/mast/
        mast.pprint-master/mast/__init__.py
        mast.pprint-master/mast/pprint/
        mast.pprint-master/mast/pprint/__init__.py
        mast.pprint-master/mast/pprint/term_utils.py
        mast.pprint-master/setup.py
https://github.com/McIndi/mast.test/archive/master.zip
        mast.test-master/
        mast.test-master/.gitignore
        mast.test-master/LICENSE
        mast.test-master/README.md
        mast.test-master/mast/
        mast.test-master/mast/__init__.py
        mast.test-master/mast/test/
        mast.test-master/mast/test/__init__.py
        mast.test-master/mast/test/test.py
        mast.test-master/setup.py
https://github.com/McIndi/mast.testsuite/archive/master.zip
        mast.testsuite-master/
        mast.testsuite-master/.gitignore
        mast.testsuite-master/README.md
        mast.testsuite-master/mast/
        mast.testsuite-master/mast/__init__.py
        mast.testsuite-master/mast/testsuite/
        mast.testsuite-master/mast/testsuite/__init__.py
        mast.testsuite-master/mast/testsuite/__main__.py
        mast.testsuite-master/mast/testsuite/integration/
        mast.testsuite-master/mast/testsuite/integration/__init__.py
        mast.testsuite-master/mast/testsuite/regression/
        mast.testsuite-master/mast/testsuite/regression/__init__.py
        mast.testsuite-master/mast/testsuite/regression/test_datapower_py.py
        mast.testsuite-master/mast/testsuite/unit/
        mast.testsuite-master/mast/testsuite/unit/__init__.py
        mast.testsuite-master/mast/testsuite/unit/test_mast_datapower_system
        mast.testsuite-master/mast/testsuite/unit/test_mast_datapower_system.py
        mast.testsuite-master/mast/testsuite/unit/test_mast_imports.py
        mast.testsuite-master/setup.py
https://github.com/mcindi/mast.timestamp/archive/master.zip
        mast.timestamp-master/
        mast.timestamp-master/.gitignore
        mast.timestamp-master/README.md
        mast.timestamp-master/mast/
        mast.timestamp-master/mast/__init__.py
        mast.timestamp-master/mast/timestamp/
        mast.timestamp-master/mast/timestamp/__init__.py
        mast.timestamp-master/setup.py
https://github.com/mcindi/mast.xor/archive/master.zip
        mast.xor-master/
        mast.xor-master/.gitignore
        mast.xor-master/README.md
        mast.xor-master/mast/
        mast.xor-master/mast/__init__.py
        mast.xor-master/mast/xor/
        mast.xor-master/mast/xor/__init__.py
        mast.xor-master/setup.py
https://github.com/tellapart/commandr/archive/master.zip
        commandr-master/
        commandr-master/.gitignore
        commandr-master/CHANGES
        commandr-master/LICENSE
        commandr-master/MANIFEST
        commandr-master/README.md
        commandr-master/commandr/
        commandr-master/commandr/__init__.py
        commandr-master/commandr/commandr.py
        commandr-master/commandr/functools_util.py
        commandr-master/example.py
        commandr-master/register_commandr_completion.sh
        commandr-master/setup.py
https://github.com/cherrypy/cherrypy/archive/master.zip
        cherrypy-master/
        cherrypy-master/.flake8
        cherrypy-master/.gitignore
        cherrypy-master/.hgignore
        cherrypy-master/.hgtags
        cherrypy-master/.pre-commit-config.yaml
        cherrypy-master/.travis.yml
        cherrypy-master/CHANGES.txt
        cherrypy-master/CONTRIBUTING.txt
        cherrypy-master/MANIFEST.in
        cherrypy-master/README.md
        cherrypy-master/cherrypy/
        cherrypy-master/cherrypy/LICENSE.txt
        cherrypy-master/cherrypy/__init__.py
        cherrypy-master/cherrypy/__main__.py
        cherrypy-master/cherrypy/_cpchecker.py
        cherrypy-master/cherrypy/_cpcompat.py
        cherrypy-master/cherrypy/_cpcompat_subprocess.py
        cherrypy-master/cherrypy/_cpconfig.py
        cherrypy-master/cherrypy/_cpdispatch.py
        cherrypy-master/cherrypy/_cperror.py
        cherrypy-master/cherrypy/_cplogging.py
        cherrypy-master/cherrypy/_cpmodpy.py
        cherrypy-master/cherrypy/_cpnative_server.py
        cherrypy-master/cherrypy/_cpreqbody.py
        cherrypy-master/cherrypy/_cprequest.py
        cherrypy-master/cherrypy/_cpserver.py
        cherrypy-master/cherrypy/_cpthreadinglocal.py
        cherrypy-master/cherrypy/_cptools.py
        cherrypy-master/cherrypy/_cptree.py
        cherrypy-master/cherrypy/_cpwsgi.py
        cherrypy-master/cherrypy/_cpwsgi_server.py
        cherrypy-master/cherrypy/_helper.py
        cherrypy-master/cherrypy/cherryd
        cherrypy-master/cherrypy/daemon.py
        cherrypy-master/cherrypy/favicon.ico
        cherrypy-master/cherrypy/lib/
        cherrypy-master/cherrypy/lib/__init__.py
        cherrypy-master/cherrypy/lib/auth.py
        cherrypy-master/cherrypy/lib/auth_basic.py
        cherrypy-master/cherrypy/lib/auth_digest.py
        cherrypy-master/cherrypy/lib/caching.py
        cherrypy-master/cherrypy/lib/covercp.py
        cherrypy-master/cherrypy/lib/cpstats.py
        cherrypy-master/cherrypy/lib/cptools.py
        cherrypy-master/cherrypy/lib/encoding.py
        cherrypy-master/cherrypy/lib/gctools.py
        cherrypy-master/cherrypy/lib/httpauth.py
        cherrypy-master/cherrypy/lib/httputil.py
        cherrypy-master/cherrypy/lib/jsontools.py
        cherrypy-master/cherrypy/lib/lockfile.py
        cherrypy-master/cherrypy/lib/locking.py
        cherrypy-master/cherrypy/lib/profiler.py
        cherrypy-master/cherrypy/lib/reprconf.py
        cherrypy-master/cherrypy/lib/sessions.py
        cherrypy-master/cherrypy/lib/static.py
        cherrypy-master/cherrypy/lib/xmlrpcutil.py
        cherrypy-master/cherrypy/process/
        cherrypy-master/cherrypy/process/__init__.py
        cherrypy-master/cherrypy/process/plugins.py
        cherrypy-master/cherrypy/process/servers.py
        cherrypy-master/cherrypy/process/win32.py
        cherrypy-master/cherrypy/process/wspbus.py
        cherrypy-master/cherrypy/scaffold/
        cherrypy-master/cherrypy/scaffold/__init__.py
        cherrypy-master/cherrypy/scaffold/apache-fcgi.conf
        cherrypy-master/cherrypy/scaffold/example.conf
        cherrypy-master/cherrypy/scaffold/site.conf
        cherrypy-master/cherrypy/scaffold/static/
        cherrypy-master/cherrypy/scaffold/static/made_with_cherrypy_small.png
        cherrypy-master/cherrypy/test/
        cherrypy-master/cherrypy/test/__init__.py
        cherrypy-master/cherrypy/test/_test_decorators.py
        cherrypy-master/cherrypy/test/_test_states_demo.py
        cherrypy-master/cherrypy/test/benchmark.py
        cherrypy-master/cherrypy/test/checkerdemo.py
        cherrypy-master/cherrypy/test/fastcgi.conf
        cherrypy-master/cherrypy/test/fcgi.conf
        cherrypy-master/cherrypy/test/helper.py
        cherrypy-master/cherrypy/test/logtest.py
        cherrypy-master/cherrypy/test/modfastcgi.py
        cherrypy-master/cherrypy/test/modfcgid.py
        cherrypy-master/cherrypy/test/modpy.py
        cherrypy-master/cherrypy/test/modwsgi.py
        cherrypy-master/cherrypy/test/sessiondemo.py
        cherrypy-master/cherrypy/test/static/
        cherrypy-master/cherrypy/test/static/404.html
        cherrypy-master/cherrypy/test/static/dirback.jpg
        cherrypy-master/cherrypy/test/static/index.html
        Traceback (most recent call last):
  File "D:\tools\mast\2.1\contrib\build-hotfix.py", line 388, in <module>
    cli.run()
  File "build\bdist.win-amd64\egg\mast\cli\__init__.py", line 251, in run
  File "D:\tools\mast\2.1\contrib\build-hotfix.py", line 330, in main
    print "\t", item.filename
  File "D:\tools\mast\2.1\anaconda\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 37-41: character maps to <undefined>

Thank you for taking the time to submit an issue, this is the only way we can continue to improve MAST in response to our customers needs.

**Comment by iLoveTux** [comment]
The offending filename is `cherrypy-master/cherrypy/test/static/Слава Україні.html`

**Comment by iLoveTux** [comment]
We have hit this issue before, I am investigating.

**Comment by iLoveTux** [comment]
OK, so after reviewing the issue, I realized that this was done on a fresh install, I think that we just need to replace build-hotfix.py with the latest.

Try this:

1. Download the newest version of build-hotfix.py [here](https://raw.githubusercontent.com/McIndi/mast.installer/master/mast/installer/files/contrib/build-hotfix.py) (right click -> Save As).
2. Place the new build-hotfix.py in contrib
3. Try the upgrade again


Let me know if this fixes the problem

**Comment by briankearney** [comment]
Ok, will let you know

**Comment by briankearney** [comment]
OK, that fixed it. Thanks.

**Comment by iLoveTux** [comment]
Perfect. We will have to do a release soon to include all these updates. I'm thinking Monday.
