### ISSUE TITLE
Issue with Pyinstaller on 32 bit python on 64 bit Windows 

### ISSUE THREAD

**Issue by iLoveTux** [McIndi/mast#59]
This issue only affects building an executable installer for MAST using PyInstaller.

This is related to [this pyinstaller issue](https://github.com/pyinstaller/pyinstaller/issues/2012). Basically when running pyinstaller (32 bit Python only) to create an executable, there is a dependency on msvcr100.dll, which isn't present on Windows by default and is not shipped with Python 2.7 (which uses msvcr90.dll).

The work-around is easy, simply execute `pip install pyinstaller==3.1.1` and it will work as normal. The real fix is to either:
- move to Python 3 (already in the works)
- wait for an upstream fix

**Comment by bastula** [comment]
Same issue occurs when building for 32-bit Python on 32-bit XP. Your work-around to downgrade to Pyinstaller 3.1.1 helps in this scenario as well.

**Comment by iLoveTux** [comment]
Thanks a lot for letting us know. Please know that we are here to help if you run into any other problems or simply need help getting started.
