### ISSUE TITLE
Option(s) to filter objects in modify-config.py

### ISSUE THREAD

**Issue by iLoveTux** [McIndi/mast#8]
Right now with [this commit](https://github.com/McIndi/mast.installer/commit/7474a1c17591ce186b3d5261c8d3e6217e7c7d5d), we have some pretty flexible ways to modify pieces of configuration from one or more objects.

This functionality allowed us to cover a prioritized use-case, which is great, but because this is such a cool way of doing things we feel that we should start expanding.

Currently you can specify a list of domains (or all-domains) or one domain, and you need to specify an object class. Now from there the only way to filter further is to limit it by object name. All or one is simply not flexible enough.

I propose a regex based filter on the object name. This will be very easy to implement, and will allow us to be fairly flexible.

Once this is implemented, we can start talking about extending the filtering functionality even further and spinning off a bunch of scripts targeted at special circumstances (like enabling a bunch of probes or adding an "all at debug" subscription to all logging targets).

@briankearney @mharden108 @steveyeof @jimb400 

Please let me know any ideas you may have below

**Comment by iLoveTux** [comment]
[pull request](https://github.com/McIndi/mast.installer/pull/7) implementing proposed change, please review and comment

**Comment by steveyeof** [comment]
Does the proposed solution require a separate regex for each unique object name? This seems like it could get cumbersome.Is it possible or useful to use an object name file as is done with StatusProviders and object classes?

**Comment by iLoveTux** [comment]
Good question.

The thing is that object names are not static. Whenever you create an object you need to give it a name. Now this name will depend upon personal taste, organizational conventions and context. The filter is only required if you want to affect certain objects of a class.

By default, this script will affect all objects which are of the specified class in the specified domain(s). The previous version would allow you to filter down to one specific object based on the name. The shortcoming was if you wanted to affect some (not all and not only one) of an object.

Let's take an example. Let's say you want to add a logging subscription to all log targets on all appliances in all domains for "all" at "debug", you could issue the following command:
```bash
./mast usrbin/modify-config.py --appliances all --credentials username:password --domains all-domains --obj-class LogTarget --no-check-hostname --mods '(vector-add)LogEvents/Priority=debug' --mods '(vector-add)LogEvents/Class=all'
```
But that will affect all log targets. What if we had a service called `ExampleService` and all log targets relevant to it had the name `ExampleService` in their own name (for instance `ExampleService-syslog` and `ExampleService-LocalFile`) and we wanted to only affect these particular log targets, well we would pass a regular expression to the `--obj-name-filter` parameter like this:

```bash
$ ./mast usrbin/modify-config.py --appliances all --credentials username:password --domains all-domains --obj-class LogTarget --no-check-hostname --mods '(vector-add)LogEvents/Priority=debug' --mods '(vector-add)LogEvents/Class=all' --obj-name-filter ExampleService
```

Then only the relevant log targets would be affected.

Also, while putting this example together, I discovered a couple of issues.

1. We have no way to specify (XML) attributes for the elements that we are adding. In this case we should have added an attribute called `class` to the `Class` element with a value of `LogLabel`.
2. We need better, more predictable behavior around `vector-adds` of elements with children. This case happened to work, but I don't know if it should have.

I'll open separate issues for these, so let's keep discussion on this issue about the `--obj-name-filter`.

**Comment by steveyeof** [comment]
Given the objective to be able to select specific multiple objects, does this imply a commonality among them? If this functionality is expected to have numerous applications would a scheme such as a default    and local "selected-obj.conf" files similar to environments.conf be a viable flexible option? Where default would allow for the "all" option and local hold a user defined set of object-names. This may be more involved than it's worth if regexes will do the job just as well though.

**Comment by iLoveTux** [comment]
It might be a good idea, but it would need to be designed very carefully.

It would need to be regex based, unless there is some great idea out there waiting to be had, but aliases for them might be useful, or perhaps a history (but this would lack context and just contain cryptic regular expressions).

We would need to have a system which beats the utility of a simple text file for this task otherwise we would be needlessly complicating things.

**Comment by steveyeof** [comment]
Let's go with what you proposed (K.I.S.S. method and all that). Thinking a little more on this, I can see that across hosts, domains, and object-classes, a file containing  groups of unique object-names could end up having a huge number of entries and be far more complex to implement than environments.conf

**Comment by iLoveTux** [comment]
That was my thinking as well, but this line of thought does spawn a few new ideas. Tell me what you think (If we think something is worth pursuing, we could open a new issue for it):

1. Low and high level functionality to pull the names of all objects of a certain class, this would allow the user to quickly see what's available to facilitate building the regular expression.
2. some sort of functionality to help the user store "cheat-sheets" or something similar embedded in our tool to help our command line users. See [here](https://github.com/chrisallenlane/cheat) for an example.

**Comment by iLoveTux** [comment]
update: looking at their [license](https://github.com/chrisallenlane/cheat/blob/master/LICENSE), we could just use their tool.

**Comment by steveyeof** [comment]
The "cheat sheets" look like something that could work pretty well, used along with ability show all objects in a given class. However we have stated in our documentation that "no scripting or Regex expressions or knowledge of DataPower CLI required for use." as among the benefits of MAST relative to competing products.If we don't wish to have differing functionality between the GUI and command line, Brian suggested possibly a "regex builder" or function that could be shelled out as part of the solution. Thoughts?

**Comment by iLoveTux** [comment]
I've never seen a regex builder work well, and I'm not entirely confident in my ability to write one that produces anything good (although I can probably produce something that works).

I understand that regexes are scary and cryptic, and having them not be a requirement is a great selling point, but at the same time this script in it's current form also requires some pretty advanced knowledge of the XML and particularly the SOMA. None of this is required to use MAST, and I would even go so far as to say that use of this from the command line is a bit hacky.

I would say that until we have a better way of solving this problem (I talked to Brian about a tree structure in a tab on the gui where you can add/modify/delete objects), let the hackers hack with the contrib script and let the users avoid regexes in the gui.

All of that being said, the innovations which made this script possible can be used to power a ton of functionality like the proposed debug logging and probes functionality without the users needing regexes.

**Comment by steveyeof** [comment]
I've heard that before about regex builders and used the Splunk version (it works, but). If this script is already best suited to users with advanced knowledge of XML and the SOMA, then it's in the realm of customized use cases that we have stated is a MAST capability not native to the product. So, I agree that the script be used for its current purpose and explore other options later.

**Comment by iLoveTux** [comment]
Well, that's how these things usually start, an easy script which allows advanced users to do almost anything which then evolves into specialized features which enable the less-experienced users perform automated tasks.

**Comment by iLoveTux** [comment]
The pull request has been merged. I am closing this issue.

Please play with the modify-config.py contrib script and open issues, I believe that we are still a long way off from having it the way it should be.

**Comment by briankearney** [comment]
How do we get the modify-config.py? IOW, is it installed if we do run
build-hotfix.py now or do we need to wait for the 2.1.1 version to be
released?

**Comment by iLoveTux** [comment]
modify-config.py should be in the contrib directory after a build-hotfix
